# Generated by Django 3.2.5 on 2021-08-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_alter_category_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40, unique=True)),
                ('product_slug', models.SlugField(unique=True)),
                ('product_desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('product_img', models.ImageField(upload_to='media/product_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
